GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjc3MDE0NTk5fQ.608lr_puQOW-s4hZVQBy68SPIKGKPchN2tAD2WVT5Cg

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjc3MDE0NTk5fQ.70rcfWYC3suW9ErkNaPvoCHts35zN8jktUXShopZbNQ"
}

###
POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjc3MDE0NTk5fQ.70rcfWYC3suW9ErkNaPvoCHts35zN8jktUXShopZbNQ"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Jim"
}